-- ==========================================================
-- Business Question 1: Overall Revenue KPI
-- Purpose:
-- Calculate the overall revenue performance of the business.
-- This provides a high-level summary including total revenue,
-- number of payments, average payment amount, minimum payment,
-- and maximum payment.
-- ==========================================================

SELECT
    ROUND(SUM(amount), 2) AS total_revenue,
    COUNT(payment_id) AS total_payments,
    ROUND(AVG(amount), 2) AS average_payment,
    ROUND(MIN(amount), 2) AS minimum_payment,
    ROUND(MAX(amount), 2) AS maximum_payment
FROM payment;

-- ==========================================================
-- Business Question 2: Revenue by Month
-- Purpose:
-- Analyze monthly revenue trends by calculating the total
-- revenue generated in each month.
-- This helps identify seasonal sales patterns and
-- business performance over time.
-- ==========================================================

SELECT
    EXTRACT(YEAR FROM payment_date) AS revenue_year,
    EXTRACT(MONTH FROM payment_date) AS revenue_month,
    ROUND(SUM(amount), 2) AS total_revenue
FROM payment
GROUP BY
    EXTRACT(YEAR FROM payment_date),
    EXTRACT(MONTH FROM payment_date)
ORDER BY
    revenue_year,
    revenue_month;

-- ==========================================================
-- Business Question 3: Revenue by Store
-- Purpose:
-- Compare the revenue generated by each store.
-- This helps evaluate store performance based on
-- revenue, payment volume, and average payment amount.
-- ==========================================================

SELECT
    s.store_id,
    ROUND(SUM(p.amount), 2) AS total_revenue,
    COUNT(p.payment_id) AS total_payments,
    ROUND(AVG(p.amount), 2) AS average_payment_amount
FROM payment p
JOIN staff st
    ON p.staff_id = st.staff_id
JOIN store s
    ON st.store_id = s.store_id
GROUP BY
    s.store_id
ORDER BY
    total_revenue DESC;

-- ==========================================================
-- Business Question 4: Revenue by Staff
-- Purpose:
-- Evaluate the revenue performance of each staff member.
-- This helps identify top-performing employees based on
-- revenue generated, payment volume, and average payment value.
-- ==========================================================

SELECT
    st.staff_id,
    st.first_name,
    st.last_name,
    ROUND(SUM(p.amount), 2) AS total_revenue,
    COUNT(p.payment_id) AS total_payments_processed,
    ROUND(AVG(p.amount), 2) AS average_payment_amount
FROM payment p
JOIN staff st
    ON p.staff_id = st.staff_id
GROUP BY
    st.staff_id,
    st.first_name,
    st.last_name
ORDER BY
    total_revenue DESC;

-- ==========================================================
-- Business Question 5: Top 10 Customers by Revenue
-- Purpose:
-- Identify the highest-value customers based on the
-- total revenue they have generated.
-- This helps the business reward loyal customers and
-- develop targeted marketing strategies.
-- ==========================================================

SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    ROUND(SUM(p.amount), 2) AS total_revenue,
    COUNT(p.payment_id) AS total_number_of_payments,
    ROUND(AVG(p.amount), 2) AS average_payment_amount
FROM customer c
JOIN payment p
    ON c.customer_id = p.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY
    total_revenue DESC
LIMIT 10;

-- ==========================================================
-- Business Question 6: Revenue by Film Category
-- Purpose:
-- Analyze revenue generated by each film category.
-- This helps identify the most profitable movie genres
-- and supports inventory and marketing decisions.
-- ==========================================================

SELECT
    ct.name AS category_name,
    ROUND(SUM(p.amount), 2) AS total_revenue,
    COUNT(r.rental_id) AS total_number_of_rentals,
    ROUND(AVG(p.amount), 2) AS average_payment_amount
FROM payment p
JOIN rental r
    ON p.rental_id = r.rental_id
JOIN inventory i
    ON r.inventory_id = i.inventory_id
JOIN film_category fc
    ON i.film_id = fc.film_id
JOIN category ct
    ON fc.category_id = ct.category_id
GROUP BY
    ct.name
ORDER BY
    total_revenue DESC;

-- ==========================================================
-- Business Question 7: Revenue by Film Rating
-- Purpose:
-- Analyze revenue generated by each film rating.
-- This helps the business understand which movie ratings
-- contribute the most revenue and rental activity.
-- ==========================================================

SELECT
    f.rating AS film_rating,
    ROUND(SUM(p.amount), 2) AS total_revenue,
    COUNT(r.rental_id) AS total_number_of_rentals,
    ROUND(AVG(p.amount), 2) AS average_payment_amount
FROM payment p
JOIN rental r
    ON p.rental_id = r.rental_id
JOIN inventory i
    ON r.inventory_id = i.inventory_id
JOIN film f
    ON i.film_id = f.film_id
GROUP BY
    f.rating
ORDER BY
    total_revenue DESC;

